export * from './user.repository';
export * from './foto.repository';
export * from './grupo.repository';
export * from './informe-fotografico.repository';
export * from './casos.repository';
export * from './dispositivos.repository';
export * from './fiscales.repository';
export * from './propietarios.repository';
export * from './tipo-dispositivos.repository';
